# docker-Specify the compose version
version: "3"

services:
  app:
    #Build a Dockerfile in the same directory
    build: .
    # https://stackoverflow.com/a/71027261
    user: ${MY_UID}:${MY_GID}
    #You can keep the container running.
    tty: true
    #Mount the files in the directory to the app directory in the container
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /etc/localtime:/etc/localtime:ro
        - /etc/hosts:/etc/hosts:ro
        - ./app/client:/app/client
        - ./app/server:/app/server
        - ./app/config.js:/app/config.js
        - ./app/index.js:/app/index.js
        - ./cache:/home/user/.config/Electron-Zotero-Item-Attachments-Report/Local Storage/leveldb
        #- /PATH-TO-ZOTERO/Zotero/:/data
    environment:
      - DISPLAY=${DISPLAY}
      - TZ=${TZ}
      - LANG=${LANG}
      #- LC_ALL=${LC_ALL} # 設了會妨礙輸入法
      - XMODIFIERS=${XMODIFIERS}
      - QT_IM_MODULE=${QT_IM_MODULE}
      - GTK_IM_MODULE=${GTK_IM_MODULE}
    # https://docs.docker.com/compose/compose-file/compose-file-v3/
    privileged: false